"""add hpo index

Revision ID: a0c12f377ce6
Revises: d89603324833
Create Date: 2026-07-19 08:29:13.932119

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a0c12f377ce6'
down_revision: str | None = 'd89603324833'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hpo_index',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hp30', sa.Float(), nullable=True),
    sa.Column('ap30', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hpo_index_time'), 'hpo_index', ['time'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hpo_index_time'), table_name='hpo_index')
    op.drop_table('hpo_index')
    # ### end Alembic commands ###
