"""initial schema

Revision ID: d89603324833
Revises: 
Create Date: 2026-07-18 22:47:00.356231

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd89603324833'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hmi_observation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('observation_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('umbra_contours', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('penumbra_contours', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hmi_observation_observation_time'), 'hmi_observation', ['observation_time'], unique=True)
    op.create_table('solar_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('observatory', sa.String(length=8), nullable=False),
    sa.Column('region', sa.Integer(), nullable=True),
    sa.Column('begin_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'type', 'observatory', 'begin_datetime', name='uq_solar_event_natural_key')
    )
    op.create_table('solar_region',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('observed_date', sa.Date(), nullable=False),
    sa.Column('region', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Integer(), nullable=False),
    sa.Column('first_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('region_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('observed_date', 'region', name='uq_solar_region_date_region')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solar_region')
    op.drop_table('solar_event')
    op.drop_index(op.f('ix_hmi_observation_observation_time'), table_name='hmi_observation')
    op.drop_table('hmi_observation')
    # ### end Alembic commands ###
